name: gym_ui
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.7.2
  gym_core:
    path: ../gym_core
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  fl_chart: ^1.1.1
  pdf: ^3.11.3
  flutter_pdfview: ^1.4.4
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
