name: gym_core
description: Core logic, models, and repositories for Gym Management App
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  http: ^1.6.0
  shared_preferences: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  intl: ^0.20.2
  go_router: ^14.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.0
  freezed: ^3.2.5
  json_serializable: ^6.12.0
